name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@main
      - name: Setup hostname
        run: |
          sed -i 's/trli.cloudns.biz/${{ secrets.CF_HOST }}/g' src/index.js
          sed -i 's/trli.cloudns.biz/${{ secrets.CF_HOST }}/g' wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production --minify src/index.js
          environment: production
