name: Deploy to Cloudflare Workers(Staging)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@mian
      - name: Publish
        uses: cloudflare/wrangler-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          command: deploy --env staging --minify src/index.js
          environment: staging
